export const mockResponse = {
  id: 4384276,
  origin: 'Amersfoort Centraal',
  origin_place_id: 'tranzer:4808862',
  destination: 'Amsterdam Centraal',
  destination_place_id: 'tranzer:4808880',
  travel_class: 2,
  train_preferred: true,
  tram_preferred: true,
  bus_preferred: true,
  subway_preferred: true,
  passengers: [
    {
      id: 3029892,
      first_name: 'John',
      last_name: 'Doe',
      age: 33,
      birth_date: '1988-11-13',
      _type: 'adult',
      email: 'john.doe@email.com',
      phone_number: '1234567890',
      gender: 'Male',
    },
  ],
  start_modality: 'walking',
  end_modality: 'walking',
  n_persons: 1,
  departure_time: '2021-10-19T14:38:16.587580+02:00',
  arrival_time: '2021-10-19T18:00:00.587580+02:00',
  journeys: [
    {
      id: 44455566678,
      type: 'transit',
      status: 'active',
      status_until: '2021-11-15T09:49:54.294671Z',
      transit_origin: {},
      total_co2: 2.81,
      transit_destination: {},
      notification_time: '2021-10-19T14:38:16.587580+02:00',
      messages: [],
      total_ticket_price: 15.41,
      total_emv_ticket_price: 14.51,
      total_ticket_price_without_extras: 14.51,
      service_fees: [
        {
          payment_method: 'Adyen',
          amount: 2.3,
          amount_currency: 'EUR',
          display_name: 'Credit card',
        },
      ],
      plan: {
        id: 1234566,
        departure_time: '2021-10-20T12:25:59+02:00',
        arrival_time: '2021-10-20T12:25:59+02:00',
        duration: '00:49:01',
        bounds: {
          southwest: {
            lat: 52.15345211656229,
            lon: 5.373564067496421,
          },
          northeast: {
            lat: 52.15345211656229,
            lon: 5.373564067496421,
          },
        },
        polyline:
          'obu~Hg_|\\s@iGKMr@oCvAyFp@eC~@_Fx@oHl@wIDaEEaEc@gN@eCR}D|BwWfBgSbAaLh@{CfCmLdBgIfA_Hp@sCvAuDzBcDrAmAfB}@bCk@nC[`B@hBZ|B|@rGdDtDjBnCjAfBZjGEtHOfC`@lCdAfBbAvAtAvChE~@lBf@~AfArEvIhc@dCfNpAbGbAvCbAnBpBfCpChBlBd@hCLxBSzAa@fA_@zBwAvB}AvFgDnLcG`KaFnHeCxCeAjEuBpC}ApF{DhN}K|L_KjBgBrMkNbJiI|AuAnE_EdIcI`FqFrCgDzDsEvAcBvB_CnHgH~GqFzCaCjKkI~U}S|KaKnWkVbN}LhPuNjNeMxYiWv^a\\xRaQxVeTzZaWlUcSvE{DtS{Q|KwJlMcKvFyDhIkGjV_Tl]uZl^s[hHaGtFsD`G}CdI}CfHmBlHiArHg@xFGnIV~Fh@rIrA~{@vO~z@lOdK~Afk@|KzYtFhWfEjY`FhJ`BzB^|IhBlXfFvZpFfNpCdBP|JlBdGt@|BTjGZtLCvIS|Ig@fC]rGyAlBg@hG{BhJcFtF_E~FkFbFyFnEcGxDaGrEwIzAeDlDwIbHwQfHwPjMaXnf@_dApNyYtMaXtv@c~AvNeZjEgJzNsY~HaPhRi`@d^at@dq@_wAfGiM~KkTvDwGlMyTvA}DdBqHlB{IhBoEbBeCzA{ArAoAnCwBn@a@xAqApEqDjCwBt@q@TbApArF]XeA~@X?^K~@w@VW}CkJJ`@cA|@{AlA_GhEyE|CqCbCaFtEyAvAeAl@gCrA_AXoBRqA?{H}@sEkAeCkAmE{CoCwC{CsEaGkLaCaFwEoKgCsHqBiH{A_HkAcHqEaX}Ty`BwFaa@mEw\\a@}DcCmQeDsQyCkMaDwQgEaY{VcxAqQ_eAwDeT_Ied@gDsPeFa\\sU}sAuTooA}Hya@yFi\\qCoRmFmZ_Kml@cBwHyHy[aIw\\oGkS{CwHeMk[gHoQ}H{RsImTsU_l@kGoOkLeTwGuLqFiKqGwKyA}B}@{@oAmA}@m@qB_AmCs@yBOgCJ{Dt@uB|@kD|Bk@l@qLrQwKhPm@t@uBlBuBzAeLvHoBb@aAHgAGaDy@kBo@eGgDyAq@iAOcACkALkSlGaF~AyItCkDxAoGxDeAn@kC`D_MfR{EdHeE|EyAbBjP_Wrp@adAdn@s`AnmCwdEdc@eq@zD_H`@}@bBwFfAkGZaDXsGF{GRmLByGMwKGgGD_@x@}Rl@_A',
        legs: [
          {
            id: 12345,
            origin: {
              lat: 52.15345211656229,
              lon: 5.373564067496421,
              name: 'Amersfoort',
              address: {
                id: 1234567,
                formatted_address:
                  'Stationsplein 39-45, 3818 Amersfoort, Netherlands',
                street: 'Stationsplein',
                house_number: '39-45',
                postal_code: '3818',
                city: 'Amersfoort',
                county: 'Utrecht',
                country: 'the Netherlands',
                country_code: 'ml',
              },
            },
            departure_time: '2021-10-20T12:26:00+02:00',
            destination: {
              lat: 52.15345211656229,
              lon: 5.373564067496421,
              name: 'Amersfoort',
              address: {
                id: 1234567,
                formatted_address:
                  'Stationsplein 39-45, 3818 Amersfoort, Netherlands',
                street: 'Stationsplein',
                house_number: '39-45',
                postal_code: '3818',
                city: 'Amersfoort',
                county: 'Utrecht',
                country: 'the Netherlands',
                country_code: 'ml',
              },
            },
            co2: 3.44,
            arrival_time: '2021-10-20T12:26:00+02:00',
            messages: [
              {
                key: 'message_key',
                type: 'info',
                title:
                  "'This operator or line is not yet available in Tranzer'",
                data: {},
              },
            ],
            agency_logo: 'https://my-server.nl/nl-operators/NS.png',
            info: 'NS Intercity; towards Rotterdam Centraal',
            additional_info: 'Intercity',
            title: 'Train towards Rotterdam Centraal',
            mode: 'Train',
            polyline:
              'bi}Hesx_@m@~@y@|REJhAx{@zb@|dBxFbh@`JnhCoJtmHlCp`@l^jyBf_A...',
            duration: '00:13:00',
            distance: 20842,
            line_number: 'Intercity',
            line_name: 'Rotterdam Centraal <-> Leeuwarden IC600',
            headsign: 'Rotterdam Centraal',
            agency: 'NS',
            delay: '+5',
            departure_platform: '4a',
            arrival_platform: '11b',
            errors: [
              {
                code: 404,
                description: 'something went wrong',
              },
            ],
            reference: '134566789',
            excluded: false,
            occupancy: '4',
            occupancy_date: '2021-10-20T12:26:00+02:00',
            tickets: [],
          },
        ],
      },
      currency: 'EUR',
      contains_purchased_tickets: true,
      is_emv_only: true,
      flex_fee: {},
      extra_fees: [
        {
          price: 14.51,
          price_currency: 'EUR',
          display_name: 'Bicycle off-peak',
        },
      ],
      total_ticket_option_price: 14.51,
      total_ticket_option_price_without_extras: 14.51,
      upsell_categories: [],
      parking_costs: '14.51',
      total_fixed_cost: '14.51',
      total_flex_cost: '14.41',
      co2_emission: '4.55',
      total_estimate_costs: '144.51',
      value_added_tax: {
        'percentage country code': {
          amount: '1.44',
          currency: 'EUR',
        },
      },
      taxi_offers: {
        id: 1234567,
        selected: false,
        vehicle_class: 'MVP',
        arrival_time: '2021-10-20T00:00:00+02:00',
        pickup_time_in_minutes: {
          min: 5,
          max: 50,
        },
        pickup_time: {
          max: '2021-10-20T00:00:00+02:00',
          min: '2021-10-20T00:00:00+02:00',
        },
        rating: {
          id: 1234567,
          score: 5,
          max: 5,
          offer: 1234567,
        },
        vehicle_attributes: {
          luggage_capacity: 333,
          max_passengers: 9,
        },
        price_info: {
          max: 2.31,
          min: 2.31,
          min_currency: 'EUR',
          max_currency: 'AUD',
        },
        company: {
          name: 'Example taxi',
          logo_url: 'base64 encoded image',
          phone_number: '+31234567890',
          license_plate: 'L-222-MV',
        },
      },
    },
  ],
};
